// services/viz/privileged/mojom/compositing/external_begin_frame_controller.mojom.js is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

'use strict';

(function() {
  var mojomId = 'services/viz/privileged/mojom/compositing/external_begin_frame_controller.mojom';
  if (mojo.internal.isMojomLoaded(mojomId)) {
    console.warn('The following mojom is loaded multiple times: ' + mojomId);
    return;
  }
  mojo.internal.markMojomLoaded(mojomId);
  var bindings = mojo;
  var associatedBindings = mojo;
  var codec = mojo.internal;
  var validator = mojo.internal;

  var exports = mojo.internal.exposeNamespace('viz.mojom');
  var begin_frame_args$ =
      mojo.internal.exposeNamespace('viz.mojom');
  if (mojo.config.autoLoadMojomDeps) {
    mojo.internal.loadMojomIfNecessary(
        'services/viz/public/mojom/compositing/begin_frame_args.mojom', '../../../public/mojom/compositing/begin_frame_args.mojom.js');
  }



  function ExternalBeginFrameController_IssueExternalBeginFrame_Params(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  ExternalBeginFrameController_IssueExternalBeginFrame_Params.prototype.initDefaults_ = function() {
    this.args = null;
    this.force = false;
  };
  ExternalBeginFrameController_IssueExternalBeginFrame_Params.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  ExternalBeginFrameController_IssueExternalBeginFrame_Params.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 24}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate ExternalBeginFrameController_IssueExternalBeginFrame_Params.args
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 0, begin_frame_args$.BeginFrameArgs, false);
    if (err !== validator.validationError.NONE)
        return err;


    return validator.validationError.NONE;
  };

  ExternalBeginFrameController_IssueExternalBeginFrame_Params.encodedSize = codec.kStructHeaderSize + 16;

  ExternalBeginFrameController_IssueExternalBeginFrame_Params.decode = function(decoder) {
    var packed;
    var val = new ExternalBeginFrameController_IssueExternalBeginFrame_Params();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.args =
        decoder.decodeStructPointer(begin_frame_args$.BeginFrameArgs);
    packed = decoder.readUint8();
    val.force = (packed >> 0) & 1 ? true : false;
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    decoder.skip(1);
    return val;
  };

  ExternalBeginFrameController_IssueExternalBeginFrame_Params.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(ExternalBeginFrameController_IssueExternalBeginFrame_Params.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStructPointer(begin_frame_args$.BeginFrameArgs, val.args);
    packed = 0;
    packed |= (val.force & 1) << 0
    encoder.writeUint8(packed);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
    encoder.skip(1);
  };
  function ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams(values) {
    this.initDefaults_();
    this.initFields_(values);
  }


  ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.prototype.initDefaults_ = function() {
    this.ack = null;
  };
  ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.prototype.initFields_ = function(fields) {
    for(var field in fields) {
        if (this.hasOwnProperty(field))
          this[field] = fields[field];
    }
  };

  ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.validate = function(messageValidator, offset) {
    var err;
    err = messageValidator.validateStructHeader(offset, codec.kStructHeaderSize);
    if (err !== validator.validationError.NONE)
        return err;

    var kVersionSizes = [
      {version: 0, numBytes: 16}
    ];
    err = messageValidator.validateStructVersion(offset, kVersionSizes);
    if (err !== validator.validationError.NONE)
        return err;


    // validate ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.ack
    err = messageValidator.validateStructPointer(offset + codec.kStructHeaderSize + 0, begin_frame_args$.BeginFrameAck, false);
    if (err !== validator.validationError.NONE)
        return err;

    return validator.validationError.NONE;
  };

  ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.encodedSize = codec.kStructHeaderSize + 8;

  ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.decode = function(decoder) {
    var packed;
    var val = new ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams();
    var numberOfBytes = decoder.readUint32();
    var version = decoder.readUint32();
    val.ack =
        decoder.decodeStructPointer(begin_frame_args$.BeginFrameAck);
    return val;
  };

  ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.encode = function(encoder, val) {
    var packed;
    encoder.writeUint32(ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.encodedSize);
    encoder.writeUint32(0);
    encoder.encodeStructPointer(begin_frame_args$.BeginFrameAck, val.ack);
  };
  var kExternalBeginFrameController_IssueExternalBeginFrame_Name = 2059012263;

  function ExternalBeginFrameControllerPtr(handleOrPtrInfo) {
    this.ptr = new bindings.InterfacePtrController(ExternalBeginFrameController,
                                                   handleOrPtrInfo);
  }

  function ExternalBeginFrameControllerAssociatedPtr(associatedInterfacePtrInfo) {
    this.ptr = new associatedBindings.AssociatedInterfacePtrController(
        ExternalBeginFrameController, associatedInterfacePtrInfo);
  }

  ExternalBeginFrameControllerAssociatedPtr.prototype =
      Object.create(ExternalBeginFrameControllerPtr.prototype);
  ExternalBeginFrameControllerAssociatedPtr.prototype.constructor =
      ExternalBeginFrameControllerAssociatedPtr;

  function ExternalBeginFrameControllerProxy(receiver) {
    this.receiver_ = receiver;
  }
  ExternalBeginFrameControllerPtr.prototype.issueExternalBeginFrame = function() {
    return ExternalBeginFrameControllerProxy.prototype.issueExternalBeginFrame
        .apply(this.ptr.getProxy(), arguments);
  };

  ExternalBeginFrameControllerProxy.prototype.issueExternalBeginFrame = function(args, force) {
    var params_ = new ExternalBeginFrameController_IssueExternalBeginFrame_Params();
    params_.args = args;
    params_.force = force;
    return new Promise(function(resolve, reject) {
      var builder = new codec.MessageV1Builder(
          kExternalBeginFrameController_IssueExternalBeginFrame_Name,
          codec.align(ExternalBeginFrameController_IssueExternalBeginFrame_Params.encodedSize),
          codec.kMessageExpectsResponse, 0);
      builder.encodeStruct(ExternalBeginFrameController_IssueExternalBeginFrame_Params, params_);
      var message = builder.finish();
      this.receiver_.acceptAndExpectResponse(message).then(function(message) {
        var reader = new codec.MessageReader(message);
        var responseParams =
            reader.decodeStruct(ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams);
        resolve(responseParams);
      }).catch(function(result) {
        reject(Error("Connection error: " + result));
      });
    }.bind(this));
  };

  function ExternalBeginFrameControllerStub(delegate) {
    this.delegate_ = delegate;
  }
  ExternalBeginFrameControllerStub.prototype.issueExternalBeginFrame = function(args, force) {
    return this.delegate_ && this.delegate_.issueExternalBeginFrame && this.delegate_.issueExternalBeginFrame(args, force);
  }

  ExternalBeginFrameControllerStub.prototype.accept = function(message) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    default:
      return false;
    }
  };

  ExternalBeginFrameControllerStub.prototype.acceptWithResponder =
      function(message, responder) {
    var reader = new codec.MessageReader(message);
    switch (reader.messageName) {
    case kExternalBeginFrameController_IssueExternalBeginFrame_Name:
      var params = reader.decodeStruct(ExternalBeginFrameController_IssueExternalBeginFrame_Params);
      this.issueExternalBeginFrame(params.args, params.force).then(function(response) {
        var responseParams =
            new ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams();
        responseParams.ack = response.ack;
        var builder = new codec.MessageV1Builder(
            kExternalBeginFrameController_IssueExternalBeginFrame_Name,
            codec.align(ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams.encodedSize),
            codec.kMessageIsResponse, reader.requestID);
        builder.encodeStruct(ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams,
                             responseParams);
        var message = builder.finish();
        responder.accept(message);
      });
      return true;
    default:
      return false;
    }
  };

  function validateExternalBeginFrameControllerRequest(messageValidator) {
    var message = messageValidator.message;
    var paramsClass = null;
    switch (message.getName()) {
      case kExternalBeginFrameController_IssueExternalBeginFrame_Name:
        if (message.expectsResponse())
          paramsClass = ExternalBeginFrameController_IssueExternalBeginFrame_Params;
      break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  function validateExternalBeginFrameControllerResponse(messageValidator) {
   var message = messageValidator.message;
   var paramsClass = null;
   switch (message.getName()) {
      case kExternalBeginFrameController_IssueExternalBeginFrame_Name:
        if (message.isResponse())
          paramsClass = ExternalBeginFrameController_IssueExternalBeginFrame_ResponseParams;
        break;
    }
    if (paramsClass === null)
      return validator.validationError.NONE;
    return paramsClass.validate(messageValidator, messageValidator.message.getHeaderNumBytes());
  }

  var ExternalBeginFrameController = {
    name: 'viz.mojom.ExternalBeginFrameController',
    kVersion: 0,
    ptrClass: ExternalBeginFrameControllerPtr,
    proxyClass: ExternalBeginFrameControllerProxy,
    stubClass: ExternalBeginFrameControllerStub,
    validateRequest: validateExternalBeginFrameControllerRequest,
    validateResponse: validateExternalBeginFrameControllerResponse,
  };
  ExternalBeginFrameControllerStub.prototype.validator = validateExternalBeginFrameControllerRequest;
  ExternalBeginFrameControllerProxy.prototype.validator = validateExternalBeginFrameControllerResponse;
  exports.ExternalBeginFrameController = ExternalBeginFrameController;
  exports.ExternalBeginFrameControllerPtr = ExternalBeginFrameControllerPtr;
  exports.ExternalBeginFrameControllerAssociatedPtr = ExternalBeginFrameControllerAssociatedPtr;
})();